include:
  - notebooks-api/compose.yaml
  - notes-api/compose.yaml

services:
  reverse_proxy:
    image: nginx:1.27.0
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - notes_app_servers_net
    depends_on:
      - nb_server
      - ns_server

networks:
  notes_app_servers_net: