name: notes_api

services:
  ns_server:
    build: 
      context: .
      target: development
    ports:
      - 3001:80
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_DB_USER}:$NOTES_DB_PASSWORD@ns_db/$NOTES_DB_NAME
    networks:
      - ns_network
    depends_on:
      - ns_db

  ns_db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: ns_volume
        target: /data/db
    networks:
      - ns_network

volumes:
  ns_volume:

networks:
  ns_network: