name: notes-api

services:
  server:
    build: 
      context: .
      target: development
    ports:
      - 3001:80
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_DB_USER}:$NOTES_DB_PASSWORD@db/$NOTES_DB_NAME
    networks:
      - ns-network
    depends_on:
      - db

  db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: ns-volume
        target: /data/db
    networks:
      - ns-network

volumes:
  ns-volume:

networks:
  ns-network: